### ISSUE TITLE
Create Deals List View

### ISSUE THREAD

**Issue by leoscribles** [zurichat/zc_plugin_company_sales_prospect#101]
Solved the issue by creating a view (DealListView) that contains a serializer (DealSerializer) and fetches data from Team Newton's https://zccore.herokuapp.com/data/read/000000000000000000000000/deals/612a3a914acf115e685df8e3/ which is currently empty at the time of solving this issue.

If the database contains data, it will return the list of deals in JSON format.

If the core database is down it will return a "TRY AGAIN LATER" message.

Live testing link: https://sales.zuri.chat/deals/list/

**Comment by leoscribles** [comment]
Solved the issue by creating a view that points to the DealSerializer and fetches data from Team Newton's https://zccore.herokuapp.com/data/read/000000000000000000000000/deals/612a3a914acf115e685df8e3/ which is currently empty at the time of solving this issue.

If the database contains data, it will return the list of deals in JSON format.

If the core database is down it will return a "TRY AGAIN LATER" message.

Live testing link: https://sales.zuri.chat/deals/list

**Comment by leoscribles** [comment]
Test link working.

**Comment by markessien** [comment]
Nice work :+1:
