### ISSUE TITLE
Setup React Application

### ISSUE THREAD

**Issue by Khadeeejah** [zurichat/zc_plugin_company_sales_prospect#110]

**Comment by Khadeeejah** [comment]
I set up a react app because we would be using Reactjs for this project

**Comment by markessien** [comment]
403 Forbidden

**Comment by Khadeeejah** [comment]
changed npm to yarn

**Comment by Khadeeejah** [comment]
@markessien we had a little glitch on our sub-domain when you clicked on the link.
you can now view it here http://sales.zuri.chat/

**Comment by markessien** [comment]
ok
