### ISSUE TITLE
Create the ProspectCreateView so user can add new prospects 

### ISSUE THREAD

**Issue by sparkle666** [zurichat/zc_plugin_company_sales_prospect#73]

**Comment by conqueror-74** [comment]
I can try this if it hasn't been assigned yet

**Comment by ALASHI1** [comment]
on it

**Comment by ALASHI1** [comment]
solved the issue by creating a model view that will create a prospect by write the data to the core database and if successful
it will return a "SUCCESS MESSAGE" and if the core database is down it will return a "TRY AGAIN LATER" message for the user to wait for the core database write function to be up and running
the link for testing this is https://sales.zuri.chat/prospects/create and the first field (id field is not required)
the code/pr can be found here  #173

**Comment by markessien** [comment]
Okay :+1:
