### ISSUE TITLE
Creation of ProspectSerializer to aid in the creation of the ProspectViews for a user

### ISSUE THREAD

**Issue by sparkle666** [zurichat/zc_plugin_company_sales_prospect#90]

**Comment by khail447** [comment]
This issue aids in the creation of Prospect views for the user as it is a requirement to be imported to each views (prospectListview, prospectCreateview, prospectDetailview and prospectDeleteview).

PR: https://github.com/zurichat/zc_plugin_company_sales_prospect/pull/146

Test-link: https://sales.zuri.chat/prospects/

**Comment by markessien** [comment]
Nice one :+1:
