### ISSUE TITLE
Create a search prospect endpoint 

### ISSUE THREAD

**Issue by Khadeeejah** [zurichat/zc_plugin_company_sales_prospect#99]
This is an endpoint that allows you to search for a particular prospect by suffixing any value to 
https://sales.zuri.chat/prospects/search/
E.g **https://sales.zuri.chat/prospects/search/muyiwa**

**Comment by temitayopelumi** [comment]
This is an endpoint that allows you to search for a particular prospect using any value of a field.

Testing link: https://sales.zuri.chat/prospects/search/

**Comment by markessien** [comment]
Nice one
